### ISSUE TITLE
Possible mods to trim

### ISSUE THREAD

**Issue by QnoisX** [CritLoren/Yggdrasil-VR#37]
There are some mods that could possibly be removed from the list to make room for new stuff.  There are only 254 slots for esp and some of these mods aren't worth the slot.  There are also some mods that could be made optional since they're purely for RP and don't need to take up the slot unless you want to use them.  Let's start off with straight up removals.

**Up for Removal**
- *Beyond Skyrim: Bruma*
While this is a decent mod, it is still unfinished.  It also requires a ton of patches.  Could be replaced with a complete experience.
- *Dawi Race* - *Bardin Goreksson* - *Dawi NPCs*
We don't use this as a PC race.  Not lore friendly?  Heights of Skyrim is better.  Bardin is so-so...  Uses like 3 esp.
- *Purchasable Store-Display Items*
Neat idea, but it doesn't give you prices or item names, just an icon.  Very easy to accidently buy items wasting money.
- *JS Rumpled Rugs*
Honestly didn't know this was a thing in game.  Doesn't seem worth an esp.  Plus, it can make rugs clip into your feet apparently.
- *Locked City Gate*
Not a fan of this one.  NPC can come and go while you stand there looking dumb.  Fast travel is already disabled, so you're just stuck.
- *Just Cast It*
Randomly failing to cast a spell with no feedback given as to why it's even happening.  Comes off as a bug, not a feature to players.
- *Beware of Darkness*
Darkness isn't well defined in game.  Just seems to randomly decide you must move slower.  Makes fire the best element.

**Make Optional**
- *Beards of Power*
Only works for PCs, so useless unless you want an impressive beard for your character.  REQ for Dawi.
- *Attraction*
Purely RP.  You should get better prices because they're attracted to you, not the other way around.  I guess it's for flirting?
- *Simpler Knock*
Brings up the menu anytime you activate a locked door even if you have the key.  Oops, let me back out.  *weird cut to black*
- *Time Flies*
I dunno, just seems strange.  You go to town to make a few items to level BS, hours pass, the vendors are now closed.  Wait or nap?
- *Pronouns*
If you want to use it, activate it.  If not?  It's just taking up an esp slot.
- *Minimalistic Character Ancestry*
Same as the last one, didn't even know this one was in the list since it doesn't prompt you.  As optional, more peeps would see it.
- *Dragonborn Speak Naturally*
Doesn't use an esp so I guess it doesn't matter.  Optional is still a good spot to put it so peeps know it's there.
- *In Your Shadow*
Neat mod completely removes elements of being Dragonborn.  But has to be opted out currently.  Better to opt in.

Finally, just some mods that could be swapped straight up.  Don't gain or lose an esp.
~~ZDO~~ -> *Shadow of Skyrim: Nemesis* -- no explanation needed
~~FLP~~ -> *NFF* -- Nethers has better support for custom followers (ignore token) and more options
~~Taina~~ -> *Shirley* -- Tiana doesn't really heal and just uses a stock voice.  Shirley looks awesome!

**Comment by m-vlad** [comment]
I'll go one by one:

Beyond Skyrim: Bruma
It adds its own worldspace, and despite not being feature complete it still adds a lot of cool new locations and quests to go through. It's not going away.
Dawi Race - Bardin Goreksson - Dawi NPCs
As part of highlighting the coolness of seeing things from different perspectives i am overruling lore friendliness in favour of having differently sized races and characters. Bardin is just an extra, the main focus is having a more varied set of characters and races to interact with. As for playable races, I manually disabled it because it sadly doesn't really work in VR. I used to provide an optional VRIK ini that kinda had dwarf-proportioned sliders, but it was a bit weird, plus it completely overrides the player set vrik and if you spent a while to adjust that it kinda sucks, so 
Purchasable Store-Display Items
Neat idea, but it doesn't give you prices or item names, just an icon. Very easy to accidently buy items wasting money.
JS Rumpled Rugs
Honestly didn't know this was a thing in game. Doesn't seem worth an esp. Plus, it can make rugs clip into your feet apparently.
Locked City Gate
Not a fan of this one. NPC can come and go while you stand there looking dumb. Fast travel is already disabled, so you're just stuck.
Just Cast It
Randomly failing to cast a spell with no feedback given as to why it's even happening. Comes off as a bug, not a feature to players.
Beware of Darkness
Darkness isn't well defined in game. Just seems to randomly decide you must move slower. Makes fire the best element.

**Comment by m-vlad** [comment]
I'll go one by one:

#### Beyond Skyrim: Bruma
It adds its own worldspace, and despite not being feature complete it still adds a lot of cool new locations and quests to go through. It's not going away.

#### Dawi Race - Bardin Goreksson - Dawi NPCs
As part of highlighting the coolness of seeing things from different perspectives i am overruling lore friendliness in favour of having differently sized races and characters. Bardin is just an extra, the main focus is having a more varied set of characters and races to interact with. As for playable races, I manually disabled it because it sadly doesn't really work in VR. I used to provide an optional VRIK ini that kinda had dwarf-proportioned sliders, but it was a bit weird, plus it completely overrides the player set vrik and if you spent a while to adjust that it kinda sucks, but I might add it back as a gameplay tip, for people who want to try something different.

#### Purchasable Store-Display Items
Better than accidentally stealing something no? I did see an issue with the price not always being visible, so I'll have to investigate that, but I don't really see the issue with having it in.

#### JS Rumpled Rugs
It was a last minute addition, it adds some nice unkemptness to the world. I don't mind clipping tbh, but I will be merging this into landscape and clutter probably.

#### Locked City Gate
Yeah understandable, I might remove it, the reasoning for its addition was a bit clumsy and it doesn't seem to have gone as planned.

#### Just Cast It
Totally agree, will remove it next version

#### Beware of Darkness
I'm on the edge on this one, I'm tempted to make it a poll but ofc everyone is likely to choose to not be inconvenienced with any such mod, despite it sometimes being more fun to work around these things. I'll consider it.

**Comment by m-vlad** [comment]
For the make optional part, having too many optional mods can be a bit cluttery, and if there's too many it can kinda become its own readme step to explain to people what each mod does and stuff, I'd rather remove a mod than make it optional.

#### Beards of Power
I might merge it with Dawi into the additional races merge, but that would cause problems with the Bardin mod.

#### Attraction
Purely RP is one of the core aspects of the list, this will stay pre-enabled.

#### Simpler Knock
It can be a huge help tho, and when paired with locked city gates I thought they'd interact quite nicely, not sure in practice. I'll be keeping this as pre-enabled still, because it can help a lot with locked locations, and it's much better to keep in mind that standing = regular citizen, sneaking = nefarious stuff than to unimmersively wait outside a dude's house to hand the quest in.

#### Time Flies
I don't see the strangeness, crafting things takes time, interacting with things takes time. One should plan their actions a bit in that regard, and pay to stay at the inn the more night they spend in town. It's a money sink, a balancing thing (can't craft 500 iron daggers and not get hungry at all or need sleep) and it helps set a pace for things, rather than it just being night or day and you not taking it into account as a player.

#### Pronouns
Same as Attraction.

#### Minimalistic Character Ancestry
I might just merge this one, and again add a gameplay tip or something of the sort.

#### Dragonborn Speak Naturally
I'd rather just mention it in a gameplay tip again.

#### In Your Shadow
Same as Attraction.


A lot of these removals and optional suggestions are understandable on one hand, but they're part of what I consider the "Yggdrasil experience" in one form or another, as said in the beginning of this message overcomplicating the optional section isn't great either, and personally I don't care for esp slots. there's already like 5-6, and if people want to add more they're welcome to modify the list as they see fit. Having to force myself to remove or disable mods just to make space for more empty slots when I could just.. use them as part of what I want to play is just unneeded stress. Considering that merging mods with scripts seems to have worked fine so far, i might make a few more, but that's not a promise.

**Comment by QnoisX** [comment]
Yep, it's totally your list, just wanted to offer some suggestions.

The main reason I like to have optional mods and free esp is because there's always new mods.  Something cool might drop any day.  A cool quest mod or maybe some armor that looks sick.  Might just want to use DBU which is 2 esp by itself.  Might need a patch esp for some bug.  It would give a little room to grow between big content patches too if we could just drop in a new mod without having to merge it.

**Comment by m-vlad** [comment]
Yeah as I said, i'm happy that so far it seems merging script mods has been a success, as long as I redirect scripts in zmerge, so I'll be considering expanding the merges and splitting a few of them a bit more.
