### ISSUE TITLE
Possible hotfix updates

### ISSUE THREAD

**Issue by QnoisX** [CritLoren/Yggdrasil-VR#50]
**Is your feature request related to a problem? Please describe.**
Just a few things that could be changed in the next hotfix update.  Mostly just reminders.

**Describe the solution you'd like**
* Default MO2 to Launch Yggdrasil instead of xEdit to cut down on confusion.
* Lower the default difficulty from Master to Expert.  (I know, "git gud")
* Rename Narsil Bindings for VR to Oculus bindings?  They don't work for Index it seems.
* Also, maybe remove any bindings for both thumbs.  More gesture options are always better.
* If possible, put the Dragonborn Awakening power on an easy gesture and have the MCM recorder message updated to tell them to use it.  Like, click in the right thumb stick.  Can that even be done?  Maybe not the best idea, seems gestures are system wide not per character?  That's dumb.
* By default, have foveated rendering set to false.  Maybe switch to the newer VR toolkit also. 
* Could throw ENB helper into the optional list.  It's just a dll.

**Is there already a mod that could solve this?**
Just settings changes mostly.

**Describe alternatives you've considered**
I dunno, not doing that stuff is an alternative.

**Additional context**
Just the most frequent problems from the Discord.

**Comment by oolatek1** [comment]
Save where i could not advance the 'enchanted to meet you' quest by going to an enchanting tabl
[Save461.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9365848/Save461.zip)
e

**Comment by CritLoren** [comment]
> Default MO2 to Launch Yggdrasil instead of xEdit to cut down on confusion.
That was an accident, it saves the last selected option when I compile.

> Lower the default difficulty from Master to Expert. (I know, "git gud")
We'll see, I'd like to look at combat for the next version so difficulty level might not be so tight.

> Rename Narsil Bindings for VR to Oculus bindings? They don't work for Index it seems.
Considering it's a nexus mod, I don't think that'd make it stand out enough. Plus it seems that people with index controllers still got it to work? I'll be redoing it with a newer tool to make it work on Index controllers for sure.

> Also, maybe remove any bindings for both thumbs. More gesture options are always better.
I have done this change since this issue was opened, the right thumbstick is cleared now, free for gestures.

> If possible, put the Dragonborn Awakening power on an easy gesture and have the MCM recorder message updated to tell them to use it. Like, click in the right thumb stick. Can that even be done? Maybe not the best idea, seems gestures are system wide not per character? That's dumb.
Next version we'll be using a main quest overhaul mod that requires a more.. active approach to the main quest, so it's good enough to just remove Dragonborn Awakening, and if someone wants to not be a dragonborn they can stop continuing the quest.

> By default, have foveated rendering set to false. Maybe switch to the newer VR toolkit also.
Yeah it seems there's quite a few people who have issues with the foveated rendering, and as you've noticed it doesn't actually help a lot, so I might just remove that. the VR toolkit doesn't work correctly I think with Open Composite, but I'll be switching away from that anyway from recommendations based on how hard it is to set it up now - with the OpenVR version breaking on existing installations and OpenXR one straight up not working correctly.

> Could throw ENB helper into the optional list. It's just a dll.
mayhaps, ENB might require extra patches however, but if it's just that - why not.
